default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: frank_development

test:
  <<: *default
  database: frank_test

production:
  <<: *default
  adapter: postgresql
